# Generated by Django 4.2.6 on 2023-10-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='GenPassword',
        ),
    ]
